apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2021-09-08T12:29:54Z"
  generation: 1
  labels:
    app: mattermost
  name: mattermost
  namespace: default
  uid: ""
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mattermost
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mattermost
    spec:
      containers:
      - image: sa2knight/mattermost:4.10.4
        imagePullPolicy: IfNotPresent
        name: mattermost
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: MM_USERNAME
            valueFrom:
              configMapKeyRef:
                name: common-env
                key: MYSQL_USER
          - name: MM_PASSWORD
            valueFrom:
              secretKeyRef:
                name: common-env
                key: MYSQL_PASSWORD
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: common-env
                key: MYSQL_DATABASE
          - name: DB_HOST
            value: mysql-0.mysql
          - name: DB_PORT_NUMBER
            value: "3306"
          - name: MM_SQLSETTINGS_DRIVERNAME
            value: mysql
          - name: MM_SQLSETTINGS_DATASOURCE
            value: $(MM_USERNAME):$(MM_PASSWORD)@tcp(mysql-0.mysql:3306)/mattermost?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s
        ports:
          - containerPort: 8065
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
