apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-scripts
data:
  setup.sh: |
    #!/bin/bash
    set -e
    [[ $(hostname) =~ -([0-9]+)$ ]]
    serverid=${BASH_REMATCH[1]}
    CONF='/mnt/conf.d/server-id.cnf'
    # Create server-id.cnf
    echo [mysqld] > ${CONF}
    if [ "${serverid}" -eq 0 ]; then
      echo "log-bin=mysql-bin" >> ${CONF}
      echo "server-id=$((100+serverid))" >> ${CONF}
    else
      echo "read_only" >> ${CONF}
      echo "server-id=$((100+serverid))" >> ${CONF}
    fi
    # Copy init-slave.sh from scripts to initdb directory
    # cp /mnt/scripts/init-slave.sh /mnt/initdb/
    # chmod +x /mnt/initdb/init-slave.sh
    exit 0
